"""empty message

Revision ID: 2216265cf8c3
Revises: d3d12fcc8b5e
Create Date: 2018-07-10 14:12:49.710052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2216265cf8c3'
down_revision = 'd3d12fcc8b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('large_data_set', sa.BOOLEAN(), nullable=True))
    op.get_bind()
    op.execute('''
          UPDATE publication 
          SET large_data_set = false 
          WHERE publication.publication NOT IN 
          ('historic-landfill', 'civil-parish-boundary', 'uk-ward-boundary', 'ancient-woodlands-england', 'listed-buildings', 'scheduled-monuments');
          ''')
    op.execute('''
      UPDATE publication 
      SET large_data_set = true 
      WHERE publication.publication IN 
      ('historic-landfill', 'civil-parish-boundary', 'uk-ward-boundary', 'ancient-woodlands-england', 'listed-buildings', 'scheduled-monuments');
      ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'large_data_set')
    # ### end Alembic commands ###
