"""empty message

Revision ID: 47fb2373b84c
Revises: f4f25e041c7e
Create Date: 2018-05-23 14:30:19.586285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fb2373b84c'
down_revision = 'f4f25e041c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area', 'name')
    # ### end Alembic commands ###
