"""empty message

Revision ID: 48980e954cf0
Revises: f4f25e041c7e
Create Date: 2018-05-16 08:55:24.620057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48980e954cf0'
down_revision = 'f4f25e041c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('area_id', sa.String(length=256), nullable=True))
    op.create_foreign_key('publication_area_fkey', 'publication', 'area', ['area_id'], ['area'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('publication_area_fkey', 'publication', type_='foreignkey')
    op.drop_column('publication', 'area_id')
    # ### end Alembic commands ###
