"""empty message

Revision ID: 5b2815aa8a55
Revises: 47fb2373b84c
Create Date: 2018-06-18 13:00:21.694007

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5b2815aa8a55'
down_revision = '47fb2373b84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('organisation_area_fkey', 'organisation', type_='foreignkey')
    op.drop_constraint('organisation_area_area_fkey', 'organisation_area', type_='foreignkey')
    op.drop_constraint('publication_attribution_fkey', 'publication', type_='foreignkey')
    op.drop_constraint('area_pkey', 'area', type_='primary')
    op.drop_constraint('attribution_pkey', 'attribution', type_='primary')
    op.drop_index('idx_area_geometry', table_name='area')

    op.alter_column('area', 'area', nullable=False, new_column_name='feature')
    op.alter_column('organisation', 'area_id', nullable=True, new_column_name='feature_id')
    op.alter_column('organisation_area', 'area', new_column_name='feature')
    op.alter_column('publication', 'attribution_id', new_column_name='copyright_id')
    op.alter_column('attribution', 'attribution', new_column_name='copyright')

    op.rename_table('area', 'feature')
    op.rename_table('organisation_area', 'organisation_feature')
    op.rename_table('attribution', 'copyright')

    op.add_column('feature', sa.Column('item', sa.String(length=256), nullable=True))
    op.add_column('feature', sa.Column('publication', sa.String(length=64), nullable=True))

    op.create_primary_key('feature_pkey', 'feature', ['feature'])
    op.create_primary_key('copyright_pkey', 'copyright', ['copyright'])
    op.create_foreign_key('organisation_feature_fkey', 'organisation', 'feature', ['feature_id'], ['feature'])
    op.create_foreign_key('organisation_feature_feature_fkey', 'organisation_feature', 'feature', local_cols=['feature'], remote_cols=['feature'] )
    op.create_foreign_key('publication_copyright_fkey', 'publication', 'copyright', ['copyright_id'], ['copyright'])

    op.add_column('publication', sa.Column('data_gov_uk', sa.Text(), nullable=True))
    op.add_column('publication', sa.Column('documentation_url', sa.Text(), nullable=True))
    op.drop_column('publication', 'url')

    op.get_bind()
    op.execute('CREATE INDEX idx_feature_geometry ON feature USING GIST (geometry gist_geometry_ops_2d);')
    op.execute('ALTER TABLE feature ALTER COLUMN data TYPE JSONB USING data::JSONB;')
    op.execute("CREATE INDEX idx_feature_data on feature using btree (CAST((data->'{properties}') AS TEXT));")
    op.execute("CREATE INDEX idx_feature_publication on feature(publication);")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('organisation_feature_fkey', 'organisation', type_='foreignkey')
    op.drop_constraint('organisation_feature_feature_fkey', 'organisation_feature', type_='foreignkey')
    op.drop_constraint('publication_copyright_fkey', 'publication', type_='foreignkey')
    op.drop_constraint('feature_pkey', 'feature', type_='primary')
    op.drop_constraint('copyright_pkey', 'copyright', type_='primary')
    op.drop_index('idx_feature_geometry', table_name='area')
    op.drop_column('feature', 'item')
    op.drop_column('feature', 'publication')

    op.alter_column('feature', 'feature', nullable=False, new_column_name='area')
    op.alter_column('organisation', 'feature_id', nullable=True, new_column_name='area_id')
    op.alter_column('organisation_feature', 'feature', new_column_name='area')
    op.alter_column('publication', 'copyright_id', new_column_name='attribution_id')
    op.alter_column('copyright', 'copyright', new_column_name='attribution')

    op.rename_table('feature', 'area')
    op.rename_table('organisation_feature', 'organisation_area')
    op.rename_table('copyright', 'attribution')

    op.create_primary_key('area_pkey', 'area', ['area'])
    op.create_primary_key('attribution_pkey', 'attribution', ['attribution'])
    op.create_foreign_key('organisation_area_fkey', 'organisation', 'area', ['area_id'], ['area'])
    op.create_foreign_key('organisation_area_area_fkey', 'organisation_area', 'area', local_cols=['area'], remote_cols=['area'])
    op.create_foreign_key('publication_attribution_fkey', 'publication', 'attribution', ['attribution_id'], ['attribution'])

    op.drop_column('publication', 'data_gov_uk')
    op.drop_column('publication', 'documentation_url')
    op.add_column('publication', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))

    op.get_bind()
    op.execute('CREATE INDEX idx_area_geometry ON area USING GIST (geometry gist_geometry_ops_2d);')
    op.drop_index('idx_feature_data')
    op.drop_index('idx_feature_publication')
    op.execute('ALTER TABLE area ALTER COLUMN data TYPE JSON USING data::JSON;')

    # ### end Alembic commands ###
