"""empty message

Revision ID: d3d12fcc8b5e
Revises: 5b2815aa8a55
Create Date: 2018-06-26 12:12:51.722596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d12fcc8b5e'
down_revision = '5b2815aa8a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind()
    op.execute("SELECT UpdateGeometrySRID('feature','geometry',4326);")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
